services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomcat-axis2
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536